#ifndef RESOURCEH
#define	RESOURCEH

#define ID_MAINICON 1

#define ID_ABOUTDIALOG 10
#define ID_CONFIGDIALOG1 11
#define ID_CONFIGDIALOG2 12

#define ID_OKBTN 20
#define ID_ABOUTLINK 21

#define ID_AUTORUNCHECK 104
#define ID_TRAYICONCHECK 105
#define ID_UPDATECHECK 106
#define ID_STAYONTOPCHECK 107
#define ID_SCREENSNAPCHECK 108
#define ID_WEEKDAYSCHECK 109
#define ID_WEEKNUMSCHECK 110
#define ID_TODAYMEMOCHECK 111
#define ID_WEEKSTARTCOMBO 112
#define ID_DATEFORMATCOMBO 113
#define ID_LANGUAGECOMBO 114

#define ID_THEMECOMBO 201
#define ID_SAVEBTN 202
#define ID_DELETEBTN 203
#define ID_ITEMCOMBO 204
#define ID_FRAMECOMBO 205
#define ID_CORNERSEDT 206
#define ID_FRAMECOLORBTN 207
#define ID_FONTCOMBO 208
#define ID_FONTSIZECOMBO 209
#define ID_ALIGNCOMBO 210
#define ID_BOLDBTN 211
#define ID_ITALICBTN 212
#define ID_UNDERLINEBTN 213
#define ID_FONTCOLORBTN 214
#define ID_MARGINEDT 215
#define ID_SPACINGEDT 216
#define ID_BACKGROUNDCOMBO 217
#define ID_BACKCOLORBTN 218
#define ID_EFFECTCOMBO 219
#define ID_EFFECTCOLORBTN 220

#endif
